### ISSUE TITLE
if-else statement expression can't get compiled

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#286] opened 2020-05-22 21:25 UTC
**Describe the bug**

Trying to compile this program fails:

```js
namespace NSMain;

entrypoint function main(): Int {
  let a = if(true) 1 else 0;
  return a;
}
```

```shell
Compiling Bosque sources in files:
ifelse.bsq
...
Transpiling Bosque assembly to C++ with entrypoint of NSMain::main...
Error -- TypeError: Cannot read property 'resultType' of undefined
Done with executable -- ifelse
```shell

```

**Comment by mrkmarron** [comment] 2020-05-22 21:59
The problem is that one of the branches is dead and the flow-sensitive typechecker can prove it (but doesn't handle it well).

We had code that would report this as a type error but that would trigger problematically when doing template instantiation. So, we commented this out and need to add a flagged version (1) to report when doing IDE checking (2) a version when we are generating code and can drop the dead branches.

**Comment by brakmic** [comment] 2020-05-22 22:03
> The problem is that one of the branches is dead and the flow-sensitive typechecker can prove it (but doesn't handle it well).
> 
> We had code that would report this as a type error but that would trigger problematically when doing template instantiation. So, we commented this out and need to add a flagged version (1) to report when doing IDE checking (2) a version when we are generating code and can drop the dead branches.

Many thanks for the explanation. I have tried to find the exact location in the source to understand the error better, but there were too many `resultType` hits. I actually wanted to use this code as an example for my 2nd article on Bosque, but now it seems better to talk about `switch-case` only. :)

**Comment by mrkmarron** [comment] 2020-05-22 22:21
The if-expression example will work if you have anything non-trivial there (the type-checker isn't that clever). So the following should work:
```
entrypoint function main(): Int {
  let x = 1;
  let a = if(x == 0) 1 else 0;
  return a;
}
```
or
```
global flag: Bool = true;

entrypoint function main(): Int {
  let x = 1;
  let a = if(NSMain::flag) 1 else 0;
  return a;
}
```

**Comment by brakmic** [comment] 2020-05-22 22:41
Awesome, many thanks. Now I can include it in the article.

**Comment by mrkmarron** [comment] 2020-06-19 04:13
It seems like this is causing recurring problems. While the right long term fix for this is a bit complex it seems like it would be better to just consider it a type error if there is an infeasible flow branch for now. I'll assign this to myself and should be able to get something done soon.

**Closed** 2020-06-19 23:28 UTC
