### ISSUE TITLE
loop exmaple

### ISSUE THREAD

**Issue by khoshroomahdi** [Microsoft/BosqueLanguage#152] opened 2019-05-02 19:57 UTC
i can't understand how can i write code without loop. I need example for this code i wrote in f#
```
let mutable a = 10
while (a < 20) do
   printfn "value of a: %d" a
   a <- a + 1
```
how can i write this code in Bosque?

**Comment by raphaelkieling** [comment] 2019-05-02 20:12
well, i found that [iterative-processing](https://github.com/Microsoft/BosqueLanguage/blob/master/docs/language/overview.md#08-iterative-processing) and [recursion](https://github.com/Microsoft/BosqueLanguage/blob/master/docs/language/overview.md#09-recursion)


Then in javascript sintax i would make using recursion:

```
let a = 10
function myLoop(a){
   if(a > 20) return a;
   a  = a + 1
   return myLoop(a)
}

myLoop(a)
```

Loop in arrays you can use `->map` or `->filter` (waiting a reduce function), and truly i not found print

**Comment by raphaelkieling** [comment] 2019-05-02 20:14
correct me please if i said bullshit

**Comment by haashirhbs** [comment] 2019-05-02 20:15
🤣🤣🤣🤣🤣Hey haha

**Comment by raphaelkieling** [comment] 2019-05-02 20:16
Oh sorry, in english bullshit is very heavy word?

**Comment by haashirhbs** [comment] 2019-05-02 20:18
Nope it's oK

**Comment by raphaelkieling** [comment] 2019-05-02 20:31
Duplicate of #152

**Comment by raphaelkieling** [comment] 2019-05-02 20:32
Duplicate of #129

**Closed** 2019-05-02 20:35 UTC
